"use client";

import { useEffect, useMemo, useState } from "react";

type Status="now"|"next"|"waiting"|"done"; type Priority="critical"|"high"|"medium"|"low"; type Project="seo"|"ciocarlia"|"dderma"|"soho"|"tekreart"; type View="work"|"home";
type Subtask={id:string;label:string;done:boolean}; type Task={id:string;client:string;project:Project;title:string;priority:Priority;status:Status;hours:number;note?:string;subtasks:Subtask[]}; type HomeItem={id:string;title:string;done:boolean;note?:string};
const seed:Task[]=[
{id:"nataly",client:"SEO · Nataly",project:"seo",title:"Promo Campaign — 3 teme / 3 limbi",priority:"critical",status:"now",hours:6,note:"Laser −50% · Endosfera −25% · Hydrafacial −20% · RU + RO + TR · Post + Story",subtasks:[{id:"n1",label:"Laser Epilation −50% — RU / RO / TR · Post + Story",done:false},{id:"n2",label:"Endosfera −25% — RU / RO / TR · Post + Story",done:false},{id:"n3",label:"Hydrafacial −20% — RU / RO / TR · Post + Story",done:false},{id:"n4",label:"Toate cele 4 limbi — scoate textul «ofertă disponibilă până în 31 august» din fiecare mărime",done:false}]},
{id:"ciocarlia",client:"Ciocârlia · Diana Roșca",project:"ciocarlia",title:"Website",priority:"high",status:"now",hours:13,note:"Principalul proiect — lucrează în blocuri de focus",subtasks:[{id:"c1",label:"Structură + pagini",done:false},{id:"c2",label:"Design responsive",done:false},{id:"c3",label:"2 cărți + autoare",done:false},{id:"c4",label:"Comandă / cumpărare",done:false},{id:"c5",label:"Blog",done:false},{id:"c6",label:"Mobile QA",done:false},{id:"c7",label:"Deploy",done:false}]},
{id:"co2",client:"D DERMA · Liliana",project:"dderma",title:"CO₂ — seria de postări",priority:"high",status:"waiting",hours:2.5,note:"Waiting for final photos from Liliana",subtasks:[{id:"d1",label:"Schimbă imaginea CO₂",done:false},{id:"d2",label:"100% nein, aber bis zu 80% definitiv ja",done:false},{id:"d3",label:"Post CO₂ — text Liliana",done:false},{id:"d4",label:"Revizie + export",done:false}]},
{id:"banner",client:"D DERMA · Liliana",project:"dderma",title:"Stand direcțional",priority:"high",status:"next",hours:1.75,note:"Stand/banner care arată direcția · confirmă dimensiunea 85 × 110 × H1163 mm",subtasks:[{id:"b1",label:"Confirmă dimensiuni",done:false},{id:"b2",label:"Preia textul trimis pe WhatsApp",done:false},{id:"b3",label:"Design + indicator de direcție",done:false},{id:"b4",label:"Pregătește fișierul pentru print",done:false}]},
{id:"soho",client:"Soho Point of Beauty",project:"soho",title:"Sticker pentru sticlă",priority:"medium",status:"next",hours:1.75,note:"Actualizează varianta cu headline-uri portocalii",subtasks:[{id:"s1",label:"Găsește design precedent",done:false},{id:"s2",label:"Actualizează serviciile",done:false},{id:"s3",label:"Verifică dimensiuni",done:false},{id:"s4",label:"Export print",done:false}]},
{id:"tek",client:"Tekreart",project:"tekreart",title:"Filament Drying Guide",priority:"medium",status:"next",hours:2.5,note:"Carousel educațional: temperatură + timp de uscare",subtasks:[{id:"t1",label:"Verifică datele Creality",done:false},{id:"t2",label:"PLA / PETG / TPU / ABS / ASA / Nylon",done:false},{id:"t3",label:"Design carousel",done:false},{id:"t4",label:"Caption + CTA",done:false}]},
{id:"highlights",client:"D DERMA",project:"dderma",title:"Instagram Highlights cleanup",priority:"low",status:"next",hours:2,note:"Haut · Körper · Laser · Injektionen · Schulungen · Presse · FAQ",subtasks:[{id:"h1",label:"Covers",done:false},{id:"h2",label:"Reorganizează stories",done:false},{id:"h3",label:"Elimină highlights redundante",done:false}]}
];
const homeSeed:HomeItem[]=[{id:"jackery-cable",title:"Caută / comandă cablu 12V pentru încărcarea Jackery de la priza auto",done:false,note:"Priza auto / brichetă (12V)"},{id:"temu",title:"Comandă pe Temu — lucrurile necesare",done:false},{id:"succulents-size",title:"Verifică spațiul pentru suportul de suculente",done:false,note:"Orientativ: 38 × 38 cm, înălțime ~150 cm"},{id:"succulents-3d",title:"Proiectează sistem vertical de vazoane pentru suculente",done:false,note:"Pentru balcon · printare 3D"}];
const columns:{key:Status;label:string;hint:string}[]=[{key:"now",label:"NOW",hint:"Lucrează aici"},{key:"next",label:"NEXT",hint:"După ce termini NOW"},{key:"waiting",label:"WAITING",hint:"Blocat / așteaptă info"},{key:"done",label:"DONE",hint:"Terminat"}];
const projectLabel:Record<Project,string>={seo:"SEO / Nataly",ciocarlia:"Ciocârlia",dderma:"D DERMA",soho:"Soho",tekreart:"Tekreart"}; const STORAGE_KEY="marina-production-board-v3",HOME_KEY="marina-home-board-v1";
function progress(t:Task){return t.subtasks.length?Math.round(t.subtasks.filter(s=>s.done).length/t.subtasks.length*100):t.status==="done"?100:0}
export default function Home(){const[tasks,setTasks]=useState<Task[]>(seed),[home,setHome]=useState<HomeItem[]>(homeSeed),[view,setView]=useState<View>("work"),[open,setOpen]=useState<string|null>(null),[ready,setReady]=useState(false);
useEffect(()=>{try{const s=localStorage.getItem(STORAGE_KEY),h=localStorage.getItem(HOME_KEY);if(s)setTasks(JSON.parse(s));if(h)setHome(JSON.parse(h))}catch{}setReady(true)},[]);useEffect(()=>{if(ready){localStorage.setItem(STORAGE_KEY,JSON.stringify(tasks));localStorage.setItem(HOME_KEY,JSON.stringify(home))}},[tasks,home,ready]);
const active=tasks.filter(t=>t.status!=="done"),hours=active.reduce((s,t)=>s+t.hours*(1-progress(t)/100),0),high=active.filter(t=>t.priority==="critical"||t.priority==="high").length,done=tasks.filter(t=>t.status==="done").length;const selected=useMemo(()=>tasks.find(t=>t.id===open),[tasks,open]);
const toggleSub=(tid:string,sid:string)=>setTasks(p=>p.map(t=>t.id!==tid?t:{...t,subtasks:t.subtasks.map(s=>s.id===sid?{...s,done:!s.done}:s)}));const move=(id:string,status:Status)=>setTasks(p=>p.map(t=>t.id===id?{...t,status}:t));const markDone=(id:string)=>setTasks(p=>p.map(t=>t.id===id?{...t,status:"done",subtasks:t.subtasks.map(s=>({...s,done:true}))}:t));
return <div className="app"><nav className="sidebar"><div className="brand">✓</div><button className={view==="work"?"navActive":""} onClick={()=>setView("work")}><span>▦</span><b>Dashboard Work</b></button><button className={view==="home"?"navActive homeActive":""} onClick={()=>setView("home")}><span>⌂</span><b>Dashboard Home</b></button></nav><main className="shell"><header><div><p className="eyebrow">{view==="work"?"PRODUCTION BOARD":"PERSONAL BOARD"}</p><h1>{view==="work"?"Ce trebuie să fac acum?":"Casă & Familie"}</h1><p className="date">{view==="work"?"Culoarea = proiectul. Prioritatea = badge-ul.":"Lucruri personale, cumpărături și proiecte pentru casă."}</p></div></header>
{view==="work"?<><section className="stats"><div><strong>{active.length}</strong><span>Active</span></div><div><strong>{high}</strong><span>High priority</span></div><div><strong>~{hours.toFixed(1)}h</strong><span>Work remaining</span></div><div><strong>{done}</strong><span>Done</span></div></section><section className="legend">{(Object.keys(projectLabel) as Project[]).map(p=><span key={p} className={`legendItem ${p}`}><i/>{projectLabel[p]}</span>)}</section><section className="board">{columns.map(col=><div className="column" key={col.key}><div className="columnTitle"><div><b>{col.label}</b><small>{col.hint}</small></div><em>{tasks.filter(t=>t.status===col.key).length}</em></div><div className="stack">{tasks.filter(t=>t.status===col.key).map(task=>{const pct=progress(task);return <article className={`card project-${task.project}`} key={task.id}><div className="meta"><span className={`projectTag ${task.project}`}>{task.client}</span><b className={`priority ${task.priority}`}>{task.priority}</b></div><h2>{task.title}</h2>{task.note&&<p>{task.note}</p>}<div className="time"><span>⏱ {task.hours}h</span><span>{pct}%</span></div><div className="bar"><i style={{width:`${pct}%`}}/></div><div className="actions"><button onClick={()=>setOpen(task.id)}>Details</button>{task.status!=="done"?<button className="check" onClick={()=>markDone(task.id)}>✓ Done</button>:<button onClick={()=>move(task.id,"next")}>Reopen</button>}</div></article>})}</div></div>)}</section></>:<section className="homeBoard"><div className="homeHead"><div><b>TO DO</b><small>{home.filter(i=>!i.done).length} rămase</small></div><span className="homeDot">●</span></div><div className="homeList">{home.map(item=><label className={`homeCard ${item.done?"homeDone":""}`} key={item.id}><input type="checkbox" checked={item.done} onChange={()=>setHome(p=>p.map(x=>x.id===item.id?{...x,done:!x.done}:x))}/><div><strong>{item.title}</strong>{item.note&&<small>{item.note}</small>}</div></label>)}</div></section>}
{selected&&<div className="overlay" onClick={()=>setOpen(null)}><aside className={`detail project-${selected.project}`} onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(null)}>×</button><span className={`projectTag ${selected.project}`}>{selected.client}</span><h2>{selected.title}</h2><div className="detailMeta"><span className={`pill priority ${selected.priority}`}>{selected.priority}</span><span>⏱ {selected.hours}h estimated</span></div>{selected.note&&<div className="note">{selected.note}</div>}<h3>Checklist</h3><div className="checklist">{selected.subtasks.map(s=><label key={s.id} className={s.done?"completed":""}><input type="checkbox" checked={s.done} onChange={()=>toggleSub(selected.id,s.id)}/><span>{s.label}</span></label>)}</div><h3>Move task</h3><div className="moves">{columns.map(c=><button key={c.key} className={selected.status===c.key?"active":""} onClick={()=>move(selected.id,c.key)}>{c.label}</button>)}</div></aside></div>}</main></div>}
